baseURL = "https://pythonprimer.com/"
languageCode = "en-us"
title = "Pyhton Primer"
theme = "digitalgarden" #
enableGoogleAnalytics = true
enableRobotsTXT = true
disqusShortname = "pythonprimer"


googleAnalytics = "UA-PROPERTY_ID"

[Params]
description = "Pyhton 101 for absolute begineers"
images = ['/digital-garden-logo.png']
enableSearch = true

[Params.newsletter]
title = ""
description = "A curated weekly digest once a week to your mailbox"

# Supports buttondown, substack and revue
provider = "buttondown"

# Buttondown - URL from share page; Refer: https://blog.buttondown.email/2019/10/11/adding-a-buttondown-subscription-form-to-webflow#getting-your-subscription-url
# Substack - URL of the newsletter homepage; Example: https://on.substack.com/
# Revue - Username
path = "https://buttondown.email/api/emails/embed-subscribe/"

[menu]
[[menu.main]]
name = 'Home'
url = '/'
weight = 1
[[menu.main]]
name = 'Python Primer'
url = '/modules'
params.header = true
weight = 2
[[menu.main]]
name = 'Python Primer'
url = '/modules'
weight = 3
[[menu.main]]
name = 'Links'
params.header = true
weight = 4

[[menu.social]]
name = 'Twitter'
url = 'https://twitter.com'
weight = 1
[[menu.social]]
name = 'GitHub'
url = 'https://github.com'
weight = 2
[[menu.social]]
name = 'LinkedIn'
url = 'https://linkedin.com'
weight = 3
[[menu.social]]
name = 'Instagram'
url = 'https://instagram.com'
weight = 4
[[menu.social]]
name = 'Dribbble'
url = 'https://dribbble.com'
weight = 5
[[menu.social]]
name = 'Codepen'
url = 'https://codepen.io'
weight = 6
[[menu.social]]
name = 'Twitch'
url = 'https://twitch.com'
weight = 7
[[menu.social]]
name = 'Email'
url = 'mailto:user@example.org'
weight = 8
[[menu.social]]
name = 'RSS'
url = '/modules/index.xml'
weight = 9


# syntax highlight settings
[markup]
[markup.highlight]
style = "dracula"
[markup.goldmark.renderer]
# Enable to include inline HTML
unsafe = true
