baseURL = "https://pythonprimer.com/"
languageCode = "en-us"
title = "Pyhton Primer"
theme = "booked" #
enableGoogleAnalytics = true
enableRobotsTXT = true
disqusShortname = "pythonprimer"

# Book theme specific options
[params]
  BookTheme = "light"
  BookToC = true
  BookSection = "python"
  BookSearch = true
  BookComments = true
  BookRepo = 'https://github.com/fahdi/pythonprimer.com'
  BookEditPath = 'edit/main'
  BookDateFormat = 'January 2, 2006'
  IsMultilingual = false
  # Improve SEO by adding your own Meta Description and Keywords
  description = "Python Primer"
  author = "Fahad Murtaza aka iSuperCoder"
  keywords = "python, algorithms, coding, programming, challenge"
  # Add Google analytics tag manager ID  
  googleAnalytics = "GTM-XXXXXXX"

[markup.goldmark.renderer]
  unsafe = true

[menu]
[[menu.before]]
  name = "Login"
  url = "/login"
  weight = 10

[[menu.before]]
  name = "Dashboard"
  url = "/dashboard"
  weight = 11  

[[menu.before]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.after]]
  name = "About"
  url = "/about"
  weight = 20

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]
  page = ["HTML"]

[build]
  writeStats = true