baseURL = "https://pythonprimer.com/"
languageCode = "en-us"
title = "Python Primer"
theme = "digitalgarden" #
enableGoogleAnalytics = true
enableRobotsTXT = true
disqusShortname = "pythonprimer"

googleAnalytics = "G-VQ6V4E6KG6"

[Params]
description = "Pyhton 101 for absolute begineers"
images = ['/digital-garden-logo.png']
enableSearch = true

[Params.newsletter]
title = ""
description = "A curated weekly digest once a week to your mailbox"

# Supports buttondown, substack and revue
provider = "buttondown"

# Buttondown - URL from share page; Refer: https://blog.buttondown.email/2019/10/11/adding-a-buttondown-subscription-form-to-webflow#getting-your-subscription-url
# Substack - URL of the newsletter homepage; Example: https://on.substack.com/
# Revue - Username
path = "https://buttondown.com/api/emails/embed-subscribe/iSuperCoder?tag=python"

[menu]
[[menu.main]]
name = 'Home'
url = '/'
weight = 1

[[menu.main]]
name = 'Python Primer'
url = '/modules'
weight = 2

[[menu.social]]
name = 'Twitter'
url = 'https://x.com/fahdmurtaza'
weight = 1
[[menu.social]]
name = 'GitHub'
url = 'https://github.com/fahdi'
weight = 2
[[menu.social]]
name = 'LinkedIn'
url = 'https://www.linkedin.com/in/fahdmurtaza/'
weight = 3
[[menu.social]]
name = 'Instagram'
url = 'https://instagram.com/iSuperCoder'
weight = 5
[[menu.social]]
name = 'Codepen'
url = 'https://codepen.io/iSuperCoder/'
weight = 6
[[menu.social]]
name = 'Email'
url = 'mailto:info@fahdmurtaza.com'
weight = 8
[[menu.social]]
name = 'RSS'
url = '/modules/index.xml'
weight = 9


# syntax highlight settings
[markup]
[markup.highlight]
style = "dracula"
[markup.goldmark.renderer]
# Enable to include inline HTML
unsafe = true
